fix: pin upgraded typescript version to fix errors compiling lodash
set version to 2.4.2 (latest) since version 2.1.6 doesn't build:

node_modules/@types/lodash/index.d.ts(9240,74): error TS2304: Cannot find name 'object'.
node_modules/@types/lodash/index.d.ts(13129,29): error TS2304: Cannot find name 'object'.
node_modules/@types/lodash/index.d.ts(20002,33): error TS2304: Cannot find name 'object'.